"""
# -*- coding: utf-8 -*-
@author: npatel
Decription: Database model for calendar events
Django settings for gms_schedule project.

Generated by 'django-admin startproject' using Django 2.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os
import socket
from django.contrib.messages import constants as messages

os.environ["PATH"] += os.pathsep + 'C:/Users/npatel/Documents/Python Scripts/graphviz-2.38/release/bin/'

HOSTNAME = socket.gethostname()
IP = socket.gethostbyname(HOSTNAME)

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

PROJECT_PATH = os.path.realpath(os.path.dirname(__file__))
DEBUG = True
SITE_ID = 1

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'qc$fz^3-6q!=_24d=)a3w!mdod4w3=6(irt5c7%r_zkm3o2c9m'

# SECURITY WARNING: don't run with debug turned on in production!
BOWER_COMPONENTS_ROOT = os.path.join(PROJECT_PATH, 'components')
BOWER_PATH = os.path.normpath('C:\\Users\\npatel\\Applications\\bower.cmd')

ALLOWED_HOSTS = ['10.1.96.157', '127.0.0.1', IP, '10.51.8.156']


# Application definition
APP_DIRS = True
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',
    'djangobower',
    'schedule',
    'django.contrib.admindocs',
    'week_scheduler',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'gms_schedule.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(PROJECT_PATH, 'templates'),
                 os.path.join(os.path.dirname(__file__),
                              'template').replace('\\', '/')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.i18n',
            ],
        },
    },
]

TEMPLATE_DIRS = (os.path.join(os.path.dirname(__file__), 'templates'),
                 os.path.join(PROJECT_PATH, 'templates'))

WSGI_APPLICATION = 'gms_schedule.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',   # 'django.db.backends.sqlite3',
        'NAME': 'gms',  # os.path.join(PROJECT_PATH, 'db.sqlite3'),
        # The following settings are not used with sqlite3:
        'USER': 'root',
        'PASSWORD': 'root',
        # Empty for localhost through domain sockets or '127.0.0.1'
        # for localhost through TCP.
        'HOST': '127.0.0.1',
        'PORT': '3311',  # Set to empty string for default.
        'OPTIONS': {
            'sql_mode': 'traditional',
        },
    },
    'logging': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(PROJECT_PATH, 'db.sqlite3'),
    },
}

DATABASE_ROUTERS = ('week_scheduler.dbrouters.HistoryLog',)


DATABASE_APPS_MAPPING = {'contenttypes': 'default',
                         'auth': 'default',
                         'admin': 'default',
                         'sessions': 'default',
                         'messages': 'default',
                         'staticfiles': 'default',
                         'week_scheduler': ['default', 'logging'],
                         }


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/
STATIC_ROOT = os.path.join(PROJECT_PATH, 'assets')

STATIC_URL = '/static/'

LOGIN_REDIRECT_URL = '/scheduler/week_calendar/1 - Bigben'

LOGOUT_REDIRECT_URL = '/accounts/login/'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'filters': {
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse'
        }
    },
    'handlers': {
        'mail_admins': {
            'level': 'ERROR',
            'filters': ['require_debug_false'],
            'class': 'django.utils.log.AdminEmailHandler'
        }
    },
    'loggers': {
        'django.request': {
            'handlers': ['mail_admins'],
            'level': 'ERROR',
            'propagate': True,
        },
    }
}

BOWER_INSTALLED_APPS = (
    'jquery',
    'jquery-ui',
    'bootstrap',
    'fullcalendar'
)


# Additional locations of static files
STATICFILES_DIRS = (
    # Put strings here, like "/home/html/static" or "C:/www/django/static".
    # Always use forward slashes, even on Windows.
    # Don't forget to use absolute paths, not relative paths.
)

# List of finder classes that know how to find static files in
# various locations.
STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    'djangobower.finders.BowerFinder',
)


MESSAGE_TAGS = {
    messages.DEBUG: 'alert-info',
    messages.INFO: 'alert-info',
    messages.SUCCESS: 'alert-success',
    messages.WARNING: 'alert-warning',
    messages.ERROR: 'alert-danger',
}

MESSAGE_STORAGE = 'django.contrib.messages.storage.fallback.FallbackStorage'

DOWNLOAD_FILE_NAME = 'scheduler_data.csv'

GRAPH_MODELS = {
  'all_applications': True,
  'group_models': True,
}