# Generated by Django 2.0 on 2019-03-11 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventLogsModel',
            fields=[
                ('event_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('stream_id', models.IntegerField()),
                ('title', models.TextField()),
                ('start', models.TextField()),
                ('end', models.TextField()),
                ('dow', models.TextField()),
                ('user_id', models.TextField()),
                ('approval_id', models.IntegerField(null=True)),
                ('status', models.TextField()),
            ],
            options={
                'db_table': 'event_logs',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='HistoryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_id', models.IntegerField()),
                ('user_id', models.TextField()),
                ('data', models.TextField()),
            ],
            options={
                'db_table': 'history',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ScheduleModel',
            fields=[
                ('event_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('game_id', models.IntegerField()),
                ('stream_id', models.IntegerField()),
                ('game_start_time', models.DateTimeField()),
                ('game_end_time', models.DateTimeField()),
                ('linked_room', models.IntegerField()),
                ('context', models.TextField()),
                ('status', models.TextField()),
                ('creation_time', models.DateTimeField()),
                ('last_updated', models.DateTimeField()),
                ('duration', models.IntegerField()),
            ],
            options={
                'db_table': 'bingo_schedule_new',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserLogging',
            fields=[
                ('event_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('user_id', models.TextField()),
                ('approval_id', models.IntegerField()),
                ('action', models.TextField()),
                ('previous_data', models.TextField()),
                ('new_data', models.TextField()),
            ],
            options={
                'db_table': 'user_activity',
                'managed': True,
            },
        ),
    ]
