# Generated by Django 2.0 on 2019-03-11 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('week_scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlogging',
            name='approval_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='userlogging',
            name='new_data',
            field=models.TextField(null=True),
        ),
    ]
