# Generated by Django 2.0 on 2019-04-01 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('week_scheduler', '0002_auto_20190311_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlogging',
            name='activity_id',
            field=models.CharField(default=0, max_length=10, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userlogging',
            name='event_id',
            field=models.CharField(max_length=10),
        ),
    ]
