# Generated by Django 2.0 on 2019-04-02 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('week_scheduler', '0005_auto_20190401_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='historymodel',
            name='creation_time',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userlogging',
            name='creation_time',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
    ]
