# Generated by Django 2.0 on 2019-04-10 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('week_scheduler', '0006_auto_20190402_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventlogsmodel',
            name='end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='eventlogsmodel',
            name='start',
            field=models.DateTimeField(),
        ),
    ]
